spring:
  application:
    name: RetailEye

  datasource:
    url: jdbc:postgresql://localhost:5432/retaileye
    username: postgres
    password: database_password
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false

  mail:
    host: smtp.mail.yahoo.com
    port: 587
    username: email_address
    password: one_time_password
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.ssl.enable: false
      mail.debug: true

ai:
  api:
    base-url: https://retaileye.ngrok.io/ai