spring:
  application:
    name: RetailEye

  datasource:
    url: jdbc:postgresql://localhost:5432/retaileye
    username: postgres
    password: Meow13@ismylove
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    open-in-view: false